# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68f643f188d8492f891405e1d842403beaf8facd6d58c6ad14a773bc0b0a775001824c252bfe18d14202fccedf2a19d4381e47c5d529745181241ede5b385919

test:
  secret_key_base: 82632e7b8c0f68c6016d62475ee9d27d9e70b0f4137c3a2e0e6fc256f7e1ae215a05284dee4037df693c5aed2e49985732c76c3dcf063671dee8118856f2d671

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
